apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: kongpluginsecret
  namespace: kong 
spec:
  provider: {{ .Values.secretProviderClass.provider }}
  parameters:
    objects: |
      {{- range $object := .Values.secretProviderClass.parameters.objects }}
      - objectName: {{ $object.objectName }}
        objectType: {{ $object.objectType }}
        {{- if $object.jmesPath }}
        jmesPath:
          {{- range $jmesPath := $object.jmesPath }}
          - path: {{ $jmesPath.path }}
            objectAlias: {{ $jmesPath.objectAlias }}
          {{- end }}  
        {{- end }} 
      {{- end }}
  {{- if .Values.secretProviderClass.secretObjects }}
  secretObjects:
  {{- range $secretObjects := .Values.secretProviderClass.secretObjects }}
  - secretName: {{ $secretObjects.secretName }}
    type: Opaque
    data:  
    {{- range $data := $secretObjects.data }}
    - key: {{ $data.key }}
      objectName: {{ $data.objectName }}
    {{- end }}
  {{- end }}
  {{- end }} 

