{{- if .Values.serviceaccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "devops-agent"
  namespace: {{ .Values.namespace }}
  {{- with .Values.serviceaccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

