{{- range .Values.namespaces }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .name }}
{{- if .annotations }}
  annotations:
{{ toYaml .annotations | indent 4}}
{{- end }}
{{- if .labels }}
  labels:
{{ toYaml .labels | indent 4 }}
{{- end }}
{{- end }}
